# Generated by Django 3.2.19 on 2025-01-06 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chef', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dishDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef.chefdetails')),
            ],
        ),
    ]
