# Generated by Django 3.2.19 on 2025-01-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Blazin Blog !', max_length=50),
        ),
    ]
